name: Build PDF and Deploy
on: [workflow_dispatch, push]
permissions:
  contents: write
jobs:
  run-and-push:
    runs-on: ubuntu-latest
    container: rubixdev42/rush-paper-tex
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        run: make init

      - name: Build
        run: make build

      - name: Archive main.pdf
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: main.pdf

      - name: Prepare GitHub Pages Deployment
        run: |
          mkdir -p dist
          mv main.pdf dist/main.pdf
          echo '<meta http-equiv="Refresh" content="0; url=main.pdf" />' >> dist/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
